package corbaConversion;


/**
* corbaConversion/IConversionRemoteOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Conversion.idl
* lundi 20 novembre 2023 14 h 59 GMT+01:00
*/

public interface IConversionRemoteOperations 
{
  double conversionMontant (double mt);
} // interface IConversionRemoteOperations
